# Analyse Data With SQLAlchemy & Pandas

**Author:** Shinin Varongchayakul

**Date:** 31 Jan 2026

## 1. Connect to the Database

In [ ]:
# Import the package
from sqlalchemy import create_engine

# Connect to the database
engine = create_engine("sqlite:///chinook.sqlite")

## 2. List the Tables

In [3]:
# Import the package
from sqlalchemy import inspect

# Get the inspector
inspector = inspect(engine)

In [5]:
# List the table names
table_names = inspector.get_table_names()

# Print the table names
print(table_names)

['Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'MediaType', 'Playlist', 'PlaylistTrack', 'Track']

In [11]:
# Get column names
columns = inspector.get_columns("Invoice")

# Print the result
for col in columns:
    print(col["name"], col["type"])

InvoiceId INTEGER
CustomerId INTEGER
InvoiceDate DATETIME
BillingAddress NVARCHAR(70)
BillingCity NVARCHAR(40)
BillingState NVARCHAR(40)
BillingCountry NVARCHAR(40)
BillingPostalCode NVARCHAR(10)
Total NUMERIC(10, 2)

## 3. Write a Query

In [36]:
# Import the package
from sqlalchemy import text

# Set a query
query = text(
    """
    SELECT 
        InvoiceId,
        InvoiceDate,
        BillingCountry,
        Total
    FROM Invoice;  
    """
)

## 4. Load the Data

In [37]:
# Import the package
import pandas as pd

# Load the table
df = pd.read_sql(
    query,
    engine
)

In [38]:
# Inspect the df
df.head()

   InvoiceId          InvoiceDate BillingCountry  Total
0          1  2009-01-01 00:00:00        Germany   1.98
1          2  2009-01-02 00:00:00         Norway   3.96
2          3  2009-01-03 00:00:00        Belgium   5.94
3          4  2009-01-06 00:00:00         Canada   8.91
4          5  2009-01-11 00:00:00            USA  13.86

## 5. Analyse

In [39]:
# Find mean total by country
(
    df
    .groupby("BillingCountry", as_index=False)
    .agg(MeanTotal=("Total", "mean"))
    .sort_values("MeanTotal", ascending=False)
)

    BillingCountry  MeanTotal
6            Chile   6.660000
12         Hungary   6.517143
14         Ireland   6.517143
7   Czech Republic   6.445714
2          Austria   6.088571
9          Finland   5.945714
16     Netherlands   5.802857
13           India   5.789231
22             USA   5.747912
17          Norway   5.660000
11         Germany   5.588571
10          France   5.574286
21          Sweden   5.517143
19        Portugal   5.517143
4           Brazil   5.431429
5           Canada   5.427857
0        Argentina   5.374286
15           Italy   5.374286
1        Australia   5.374286
8          Denmark   5.374286
23  United Kingdom   5.374286
18          Poland   5.374286
20           Spain   5.374286
3          Belgium   5.374286